In [1]:
from dojo import Dojo
from tf_agents.environments import suite_gym, tf_py_environment
from tf_agents.networks.q_network import QNetwork

In [2]:
env = suite_gym.load('CartPole-v1')
env = tf_py_environment.TFPyEnvironment(env)
env.reset()

TimeStep(
{'discount': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 'observation': <tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[ 0.02922186, -0.0438842 ,  0.04088789,  0.04237979]],
      dtype=float32)>,
 'reward': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 'step_type': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>})

In [3]:
q_net = QNetwork(env.observation_spec(), env.action_spec())

In [4]:
%load_ext tensorboard
%tensorboard --logdir tensorboard

In [5]:
dojo = Dojo(q_net, env)
dojo.train(10000)

Instructions for updating:
Use `tf.data.Dataset.counter(...)` instead.
Instructions for updating:
Use `as_dataset(..., single_deterministic_pass=False) instead.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.foldr(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.foldr(fn, elems))
step = 200: loss = 11.991689682006836 return = 9.5
step = 400: loss = 31.53302574157715 return = 17.0
step = 600: loss = 4.539178848266602 return = 26.5
step = 800: loss = 4.036090850830078 return = 57.400001525878906
step = 1000: loss = 4.176935195922852 return = 45.5


KeyboardInterrupt: 